language: python
sudo: true
cache: false
python:
    - '3.3'

install:
  - sudo apt-get install -y python3-dev
  - sudo apt-get install -y portaudio19-dev
  - pip install -U tox==2.3.0 coveralls==1.1

script:
  - coverage erase
  - tox
after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - a.vara.1986@gmail.com