language: python

install:
  - pip install -q --use-mirrors tox==2.3.0

script:
  - coverage erase
  - tox
after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - a.vara.1986@gmail.com