# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('djgozokia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gozokiachat',
            name='type',
        ),
        migrations.AddField(
            model_name='gozokiachat',
            name='rule',
            field=models.CharField(choices=[('O', 'Gozokia'), ('I', 'User')], default=None, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gozokiachat',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gozokiachat',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Gozokia'), ('I', 'User')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gozokiachat',
            name='text',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='gozokiachat',
            name='type_rule',
            field=models.CharField(choices=[('O', 'Gozokia'), ('I', 'User')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
